_BASE_: ../vitl_336.yaml
MODEL:
  SEM_SEG_HEAD:
    TRAIN_CLASS_JSON: "datasets/mv65.json"
    TEST_CLASS_JSON: "datasets/mv65.json"
    NUM_CLASSES: 65
    IGNORE_VALUE: 65
DATASETS:
  TRAIN: ("mv_sem_seg_train",)
  TEST: ("mv_sem_seg_val",)
SOLVER:
  IMS_PER_BATCH: 2
  LR_SCHEDULER_NAME: WarmupCosineLR
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  WARMUP_METHOD: "linear"
  WEIGHT_DECAY: 0.00001
  BASE_LR: 0.0001
  MAX_ITER: 6000
  BACKBONE_MULTIPLIER: 0.0
  CLIP_MULTIPLIER: 1.0
  CHECKPOINT_PERIOD: 100000
INPUT:
  MIN_SIZE_TRAIN: (384, )
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 0
  MAX_SIZE_TRAIN: 3984
  MAX_SIZE_TEST: 3984
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (384, 384)
  SIZE_DIVISIBILITY: 384
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_semantic"
TEST:
  EVAL_PERIOD: 100000
DATALOADER:
  NUM_WORKERS: 4