_BASE_: vitl_336.yaml
SOLVER:
  CHECKPOINT_PERIOD: 100000
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  MAX_ITER: 20000
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 1000
  WEIGHT_DECAY: 0.00001
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BACKBONE_MULTIPLIER: 0.0
  CLIP_MULTIPLIER: 1.0
INPUT:
  MIN_SIZE_TRAIN: (384, )
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (384, 384)
  SIZE_DIVISIBILITY: 384
  DATASET_MAPPER_NAME: "mask_former_semantic"
TEST:
  EVAL_PERIOD: 100000
DATALOADER:
  NUM_WORKERS: 4
SEED: 1000