_BASE_: ../vitl_336.yaml
MODEL:
  SEM_SEG_HEAD:
    TRAIN_CLASS_JSON: "datasets/cs19.json"
    TEST_CLASS_JSON: "datasets/cs19.json"
    NUM_CLASSES: 19
DATASETS:
  TRAIN: ("acdc-rain_sem_seg_train",)
  TEST: ("acdc-rain_sem_seg_val", "acdc-fog_sem_seg_val", "acdc-snow_sem_seg_val", "acdc-night_sem_seg_val",)
SOLVER:
  IMS_PER_BATCH: 2
  LR_SCHEDULER_NAME: WarmupCosineLR
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  WARMUP_METHOD: "linear"
  WEIGHT_DECAY: 0.0001
  BASE_LR: 0.0001
  MAX_ITER: 2000
  BACKBONE_MULTIPLIER: 0.0
  CLIP_MULTIPLIER: 1.0
  CHECKPOINT_PERIOD: 100000
INPUT:
  MIN_SIZE_TRAIN: (384, )
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1080
  MAX_SIZE_TEST: 1920
  MAX_SIZE_TRAIN: 1920
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (384, 384)
  SIZE_DIVISIBILITY: 384
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_semantic"
TEST:
  EVAL_PERIOD: 500000
DATALOADER:
  NUM_WORKERS: 4
SEED: 250